### PR TITLE
Possible mktime tweak.

### PR DESCRIPTION
**Pull request by abalkin**

### CODE REVIEW

**Comment by abalkin** [comment]
@tim-one - Tim, what do you think of this tweak?

**Comment by tim-one** [comment]
Looks nice!  Does it work? ;-)

**Comment by abalkin** [comment]
> Does it work?

It does, but since you are asking, I am not sure it is a good idea to write code like this.  Maybe I'll structure C code this way.  I suspect **goto** will be handy.

**Comment by tim-one** [comment]
I prefer clarity, and the original is a bit clearer due to cleaner separation of cases.  But not a whole **lot** clearer - happy either way.

**Pull request merged**
